### ISSUE TITLE
scagd_albedo fails for version < 2018b

### ISSUE THREAD

**Issue by mikedurand** [edwardbair/ParBal#1]
The "all" function changed in release 2018b. 

These lines were failing for me in release 2018a:

addRequired(p,'r',@(x) all(x >= 1 & x < 2000,'all'))
addRequired(p,'mu0',@(x) all(x >= 0 & x <= 1,'all'))

For my application, I changed them to:

addRequired(p,'r',@(x) all(x >= 1 & x < 2000))
addRequired(p,'mu0',@(x) all(x >= 0 & x <= 1))

**Comment by edwardbair** [comment]
Wow, I really got to closing this issue quickly. Thanks again for the info!
